#!/usr/bin/env python3
import sys
import re
import pyperclip
from bs4 import BeautifulSoup

user_file = sys.argv[1]

with open(user_file) as f:
    soup = BeautifulSoup(f, "html.parser")
    pre = soup.find_all("pre")

tags = re.compile(r"\[?<[^>]+>\]?")  # Regex to find tags + "[" + "]"


def remove_tags(text):

    """Removes the html tags from the file
    generated by the OCR app, strips
    line breaks and copies the relevant
    text to the clipboard"""

    notags = tags.sub("", text)  # Strip tags
    without_line_breaks = notags.replace("\n", " ")  # Strip line breaks
    pyperclip.copy(without_line_breaks)  # Copy text to clipboard
    print("Parsed text copied to clipboard!")
    return without_line_breaks


remove_tags(str(pre))
